#cloud-config
package_upgrade: true
timezone: Asia/Tokyo
locale: ja_JP.utf8
write_files:
- content: |
    server {
        listen 80;
        root /usr/share/nginx/html/food-app/public;
        index index.php index.html index.htm;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
  path: /etc/nginx/conf.d/default.conf
  owner: root:root
  permissions: '0644'
- content: |
    mysql -u root "-p$(grep -oP '(?<=root@localhost\: )\S+' /var/log/mysqld.log)" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${DBPassword}'" --connect-expired-password
    mysql -u root "-p${DBPassword}" -e "CREATE USER '${DBUser}'@'%' IDENTIFIED BY '${DBPassword}'"
    mysql -u root "-p${DBPassword}" -e "GRANT ALL PRIVILEGES ON *.* TO '${DBUser}'@'%'"
    mysql -u root "-p${DBPassword}" -e "FLUSH PRIVILEGES"
    mysql -u root "-p${DBPassword}" -e "CREATE DATABASE ${DBName}"
  path: /tmp/resetmysql.sh
  owner: root:root
  permissions: '0500'
runcmd:
  - yum install -y git
  - yum remove -y mariadb-libs
  - yum localinstall https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm -y
  - yum-config-manager --disable mysql80-community
  - yum-config-manager --enable mysql57-community
  - yum install -y mysql-community-server
  - amazon-linux-extras install nginx1
  - amazon-linux-extras install php7.3
  - yum install -y php-xml && yum install -y php-mbstring
  - export HOME=/root && /usr/bin/curl -s https://getcomposer.org/installer | /usr/bin/php && mv composer.phar /usr/local/bin/composer
  - cd /usr/share/nginx/html/ && git config --global user.name ${GitUser} && git config --global user.email ${GitEmail} && git clone https://${GitUser}:${GitPassword}@github.com/siwai0208/food-app
  - cd /usr/share/nginx/html/ && chown -R ec2-user:ec2-user food-app
  - cd /usr/share/nginx/html/food-app && chmod -R 777 storage && chmod -R 777 bootstrap/cache/
  - cd /usr/share/nginx/html/food-app && sudo -u ec2-user /usr/local/bin/composer update
  - sed -i s@'listen = /run/php-fpm/www.sock'@'listen = 127.0.0.1:9000'@g /etc/php-fpm.d/www.conf
  - systemctl start mysqld && systemctl enable mysqld
  - echo validate_password_policy=LOW >> /etc/my.cnf
  - systemctl restart mysqld
  - /tmp/resetmysql.sh
  - cd /usr/share/nginx/html/food-app && cp .env.example .env
  - cd /usr/share/nginx/html/food-app && sed -i s/'APP_NAME=Laravel'/'APP_NAME="Food Delivery APP"'/g .env
  - cd /usr/share/nginx/html/food-app && sed -i s/'DB_PASSWORD='/'DB_PASSWORD=${DBPassword}'/g .env
  - cd /usr/share/nginx/html/food-app && php artisan key:generate
  - cd /usr/share/nginx/html/food-app && php artisan config:cache
  - cd /usr/share/nginx/html/food-app && php artisan migrate
  - cd /usr/share/nginx/html/food-app && php artisan db:seed
  - systemctl start php-fpm.service && systemctl start nginx.service
  - systemctl enable php-fpm.service && systemctl enable nginx.service
final_message: "The system is finally up, after $UPTIME seconds"
